using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebApiProject.Models
{
// Job.cs
public class Job
{
    [Key]
    public int Id { get; set; }
    public string Code { get; set; } = Guid.NewGuid().ToString(); // Autogenerated code using GUID
    [Required(ErrorMessage = "Title is required")]
    public string Title { get; set; }
    public string Description { get; set; }
    public int LocationId { get; set; }
    public int DepartmentId { get; set; }
    public DateTime ClosingDate { get; set; }

    // Navigation properties
    public Location Location { get; set; }
    public Department Department { get; set; }
}

}